
spring:
  datasource:
    url: jdbc:mysql://101.43.93.50:3306/spring?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Xzk_336699369
mybatis:
  #config-locations: mybatis/mybatis-config.xml
  mapper-locations: com/wjc/maker/mapper/*.xml
  type-aliases-package: com.wjc.maker.mapper.AuthorMapper